# Generated by Django 4.0 on 2023-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemployee',
            old_name='emp_id',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='salary',
        ),
        migrations.AddField(
            model_name='addemployee',
            name='profile',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
