# Generated by Django 4.0 on 2023-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0002_rename_emp_id_addemployee_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('service', models.CharField(max_length=50, null=True)),
                ('comments', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadDesigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('service_type', models.CharField(max_length=50, null=True)),
                ('design_photo', models.FileField(null=True, upload_to='documents/')),
            ],
        ),
    ]
