# Generated by Django 4.0 on 2023-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0003_givefeedback_uploaddesigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('book_id', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('paid_date', models.DateField(null=True)),
                ('provider_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='service_type',
        ),
        migrations.AddField(
            model_name='addbooking',
            name='provider_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
