# Generated by Django 4.0 on 2023-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0004_addpayment_remove_addemployee_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooking',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='addbooking',
            name='service',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
