# Generated by Django 4.0 on 2023-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0005_alter_addbooking_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbooking',
            name='payment_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
